---
- hosts: all
  become: yes
  vars:
    nginx_file: ../nginx/nginx.conf

  tasks:
    - name: Apply Nginx template
      template:
        src: "{{ nginx_file }}"
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted